### ISSUE TITLE
provide a way to bake the jenkins version + plugins into a docker image

### ISSUE THREAD

**Issue by jstrachan** [ndeloof/jenkinsfile-runner#2]
its looking like the runner downloads a new jenkins war on each build. it would be nice to have a way to easily create different docker images which bake in specific versions of jenkins along with plugins; so we could have, say, 2 images for different jenkins versions; or use different images for different sets of plugins etc.

I guess we may need a few different docker images? e.g. a 'dynamic latest jenkins' flavour or a static flavour where folks can define the versions they wanna use to bake a specific version?

e.g. it'd be nice to create a Jenkins X quickstart that lets folks tinker with the jenkins version number + plugins.txt to create an immutable image that can then be versioned + used across a number of knative builds

**Comment by ndeloof** [comment]
Current approach is to rely on a volume to cache downloads, see https://github.com/ndeloof/jenkinsfile-runner/blob/master/knative/build-hello.yaml

**Comment by jstrachan** [comment]
the docker/kubernetes approach to containers is to bake immutable images which can be easily run on any node. Using PVs are brittle - you can typically only use 1 PV per container at once, so you need to create a PV per build instance which is not ideal.

It also slows down your build; if you are using the same jenkins version + plugins for 1000 builds a day, you don't wanna be downloading that to 1000 PVs each time

**Comment by ndeloof** [comment]
For sure we can bake custom docker images with jenkins-core + plugins pre-installed, but this brings unmanageable exponential combinations, and we will need to let end-user prepare those images by themselves.

> you can typically only use 1 PV per container at once
>  if you are using the same jenkins version + plugins for 1000 builds a day, you don't wanna be downloading that to 1000 PVs each time

True because you assume use of *Persistent* (replicated, distributed, etc) Volumes, which come with those limitations in addition to performance penalties. We only need a local volume we can reuse on same node between pods, so the use of a hostPath in my sample.

I'm really surprised nobody came with  "cache" volume types. I never got feedback about https://github.com/kubernetes/kubernetes/issues/58245. We will need something like this for maven / npm / * dependency resolution for efficient builds. Maybe we need to design such extended k8s component by ourself ? 

Another (simpler ?) option is to deploy a DaemonSet download cache service, @ydubreuil experiments such a agressive cache for maven dependencies and this resulted in a significant build time reduction relying on plain transient workspaces.

**Comment by ndeloof** [comment]
Maybe it would make sense to create a custom [CSI](https://kubernetes.io/docs/concepts/storage/volumes/#csi) to provide such a "cache" volume based on a localhost transient folder. This would be helpful both for this jenkinsfile-runner download issue, but also for all other dependency caches. wdyt @jstrachan ? Do you know any k8s community tool to offer such a feature?

**Comment by jstrachan** [comment]
The docker image is itself an immutable cache which can be used on any node without adding per-host volumes or daemonsets etc - the whole of kubernetes is designed to version and cache these 'volumes' with layering and so forth - we don't need to try re-invent what docker has done here. 

We just need a reliable way to create docker images with jenkins + plugins on - which is true for vanilla stand alone jenkins and jenkinsfile runner. If a user were to pick a bad combination of jenkins version + plugins and builds fail; then thats there issue - they can try another combination ;)


Maybe another approach is for the docker build process to use latest of jenkins + plugins each time - then we use the history of docker images created as a way to go back in time to keep around older versions/permutations.

In this way you'd not be able to, say, add/remove a plugin on an old version of jenkins, but at least you'd be able to move forwards in terms of plugin combinations/jenkins versions while still being able and reuse builds on old runner versions.

e.g. imagine a git repo with a plugins.txt which just lists the plugins required. We kick off a build and we get, say, 

`myjenkinsrunnner:2.121.2.1` 

edit the plugins.txt we get....

`myjenkinsrunnner:2.121.2.2`

if there's a new jenkins release we could retrigger the build we may get...

`myjenkinsrunnner:2.122.0.1`

I guess whether or not the major jenkins version is in the docker image version or not - we'd have a sequence of versioned docker images; builds can then incrementally move forwards through time while keeping old builds around if they are required. e.g. a new jenkins version may break a build; so some older images may be required.

Folks may need a few flavours of runners, for different sets of plugins - but at least this way we've a simple way of moving forwards in time with the latest versions of things; allowing different selection of versions - while keeping old permutations that did work around as a backup

Incidentally it might be nice to add labels or generate a manifest in the generated docker image with the jenkins versions + plugins + versions; so folks can easily compare runner images? e.g. if folks hit an issue with one particular runner image it might help them navigate the sequence of images to figure out what the issue is etc?

**Comment by ndeloof** [comment]
@jstrachan what you suggest is probably feasible with a BuilderTemplate:
step 1 : bake runner image based on plugins.txt and latest LTS 
step 2 : run jenkinsfiler-runner based on image just created

**Comment by jstrachan** [comment]
what kinda scares me is jenkins + all the plugins can change at any time across all of your builds and you have no possible way to use a docker image that used to work the day before.

I hear you though; folks might not want to go to such lengths of building their own images. (though the docker way of using docker is usually for folks to create their own images ;).

OK here's another approach....

What if the jenkinsfile runner image had a nightly build and if any plugin or jenkins versions have changed, it does a new release of a new image each day and includes all the plugin jars (but not enabled). Then we have a daily cache of jenkins + plugins in a versioned docker image each day. Though if folks want the latest they use the `latest` label - or folks can use a specific known version.

Then in a git repo for a pipeline, folks can add a plugins.txt to list the plugins enabled by the runner.

Then folks can stick on latest - there's no caching issues (we reuse the docker caches today) and folks can pull always and so forth (kubernetes lets you pull on each build if you want) - but folks can still go back in time to a known working image if they hit issues?

**Comment by jstrachan** [comment]
then whether folks use `latest` or folks use a specific image tag, the build can start immediately - we still have latest moving forward aggressively as new jenkins/plugins releases happen - and folks can easily - in each build - enable/disable plugins using a `plugins.txt` - but we have immutable infrastructure + versioning for stability

**Comment by jstrachan** [comment]
putting all the plugin jars in the base image, then enabling the combination from `plugins.txt` avoids having to download anything so should be really fast to startup. (could even use symlinks if those are faster).

then having a stream of jenkinsfile runner images we could use the common docker approach of having a few latest images. e.g. `latest`, `2.latest`, `2.121.latest` or `2.121.1`, `2.121.2` etc - then folks can go to different levels of latest

**Comment by ndeloof** [comment]
> what kinda scares me is jenkins + all the plugins can change at any time across all of your builds and you have no possible way to use a docker image that used to work the day before.

this won't happen, as you provide a plugins.txt file plugins won't change without your control. Same for jenkins-core version : by default jenkinsfile-runner uses latest LTS, but the actual version being ran should be controlled by an env variable. 

> putting all the plugin jars in the base image, then enabling the combination from plugins.txt avoids having to download anything

do you mean ALL plugins from update center being bundled by default ? This would make a HUGE image (Gbs) as we don't just need latest plugin (which would be few Gb already) but all versions : `plugins.txt` is there not just to define enabled plugins, but also *VERSION* of plugins being enabled.. 

Also consider many users have custom plugins not hosted on OSS update center. 

What you suggest is comparable to suggest `maven` image should contain a bundled copy of maven central repository. This would avoid downloads for sure, but for the price of downloading an initial TB large docker image. I'm still convinced we need some cache support in kubernetes, and "immutability" only applies to "service" containers. A `build` is a very specific beast.

**Comment by jstrachan** [comment]
>> what kinda scares me is jenkins + all the plugins can change at any time across all of your builds and you have no possible way to use a docker image that used to work the day before.

> this won't happen, as you provide a plugins.txt file plugins won't change without your control. Same for jenkins-core version : by default jenkinsfile-runner uses latest LTS, but the actual version being ran should be controlled by an env variable.

right now every time I run the exact same docker image of jenkinsfile runner it downloads the latest version of jenkins and the latest version of the plugins right? 

what would be more docker-like would be to have a stream of jenkisnfile-runner docker images, so you can pick a specific version of LTS and know each build will use that exact jenkins version and it'll never change. If you want to use the latest version all the time, use `latest` docker image tag. If you wanna stay on, say, `2.121` then just use that docker image tag  - like the upstream jenkins image versions: https://hub.docker.com/r/jenkins/jenkins/tags/

So using docker image tags for the jenkins version seems to make the most sense for the jenkinfile image too; it can have similar tag strategies.

In terms of the plugins themselves I guess we have a few options....

* on each build download the plugins using latest versions 
* on each build download the plugins using the version numbers included inside the base image (so each jenkinsfile runner image can include the latest known working plugins for the LTS version) - so at least the plugin versions stay consistent while the user uses the same docker image 
* let users specify the plugin versions
* let users bake whatever plugins they want into their own image using a base jenkinsfile image + ONBUILD
* include a set of plugins in the base image (maybe 'Essentials' only?) so that no downloading is required

We've got the dynamic version already - I guess we need to ponder what options we provide. Certainly from the Jenkins X perspective we want to be able to take a static image of jenkins + plugins and then layer on other tools for our pipelines. So having the totally dynamic + totally static sounds a reasonable approach to start with. 

I wonder is there an easy way right now we could freeze the plugin versions in the jenkinsfile image so that the plugin versions don't change until you change the image tag? (when not using `latest`)?

**Comment by jstrachan** [comment]
> > putting all the plugin jars in the base image, then enabling the combination from plugins.txt avoids having to download anything

> do you mean ALL plugins from update center being bundled by default ? This would make a HUGE image (Gbs) as we don't just need latest plugin (which would be few Gb already) but all versions : plugins.txt is there not just to define enabled plugins, but also VERSION of plugins being enabled..

BTW I didn't mean to include every version of every plugin ever - more just the latest known good plugin version only. We could easily filter the list of plugins we support in this model too; e.g. only the common/essentials ones. 

Its a tradeoff - downloading every plugin on every build versus putting a known working version of the common plugins into the baser image

**Comment by ndeloof** [comment]
Give cache volume a try ;)


Le sam. 11 août 2018 à 11:44, James Strachan <notifications@github.com> a
écrit :

**Comment by jstrachan** [comment]
as i've said, docker images are the best universal versioned cache volume, so for Jenkins X I'd like a way to specify the version of jenkins + plugins and cache them in a single docker image - we can then use that as a stable base to add other tools on top for use by the pipelines; then update Jenkins X in a known stable way.

We can leave knative build folks who use jenkinsfile-runner to figure out a way to try mimic docker image caching without using docker images  ;)

So how can I best create a `Dockerfile` that bakes a jenkins version + set of plugins on to disk and disable the downloading-on-the-fly behaviour? 

I'm totally fine if you don't want to create stable immutable images as part of the jenkinsfile project; but it'd be nice to provide instructions for those folks who do want to create their own stable immutable images

**Comment by ndeloof** [comment]
> docker images are the best universal versioned cache volume

Seem we disagree on this. 

> So how can I best create a Dockerfile that bakes a jenkins version + set of plugins on to disk and disable the downloading-on-the-fly behaviour?

can point `-cache` to a location within image, and get it populated as image is built using your preferred download technique. jenkinsfile-runner should also offer a `-offline` option to avoid checking for updates.

**Comment by ndeloof** [comment]
Right, I created #3 for it

Le sam. 11 août 2018 à 13:23, James Strachan <notifications@github.com> a
écrit :

**Comment by ndeloof** [comment]
https://github.com/ndeloof/jenkinsfile-runner/issues/3 implemented by 5d5996f6a0ca29c449a651aae0006dcf818931f6
